"""Scraper registry.

Each scraper is a pure function `scrape(client) -> list[Offering]` keyed by its
provider slug (see providers.json). The runner walks this map.
"""

from __future__ import annotations

from collections.abc import Callable

import httpx

from intensive_dance.models import Offering

from . import (
    abc_dance,
    abt_jko_school,
    academie_danse_biarritz,
    academie_ete_nice,
    academie_princesse_grace,
    academie_theilaia,
    accademia_iacopini,
    accademia_internazionale_coreutica,
    accademia_teatro_alla_scala,
    akademia_sztuki_baletowej,
    alberta_ballet_school,
    american_midwest_ballet,
    art_ballet_gdynia,
    art_in_motion_munich,
    art_of_ballet_summer_course,
    art_studio_danza,
    arteballetto,
    associazione_europea_danza,
    ateneo_della_danza,
    attitude_ballet_studios,
    australian_ballet_school,
    baletni_akademie_pollertova,
    ballet_ireland,
    ballet_ruso_barcelona,
    ballet_summer_course_budapest,
    ballet_workshops_bucharest,
    balletstage,
    ballett_dortmund,
    balletto_di_roma,
    ballettratten,
    bayer_ballet_academy,
    benedict_manniegel,
    bobbio_summer_ballet_intensive,
    bolshoi_summer_intensive_tokyo,
    boston_ballet_school,
    brussels_international_ballet,
    bubenicek_masterclasses,
    canadas_national_ballet_school,
    central_school_of_ballet,
    centro_formazione_aida,
    centro_formazione_danza_verona,
    centrum_sztuki_tanca,
    conservatorio_annarella,
    cords_dance,
    corella_dance_academy,
    dam_danza_torino,
    dance_and_fashion_cic,
    dbft_sommerakademie,
    dd_masterclass_japan,
    dresden_summer_dance,
    dutch_national_ballet_academy,
    ecole_danse_opera_paris,
    elmhurst_ballet_school,
    english_national_ballet_school,
    escola_bolshoi_brasil,
    europaballett_danceflash,
    finland_international_summer_ballet_school,
    finnish_national_ballet,
    fondazione_monreart,
    fouette,
    frankfurt_ballet_masterclasses,
    goh_ballet_academy,
    gradpro_summer_intensive,
    gyori_balett_dance_intensive,
    hong_kong_academy_of_ballet,
    houston_ballet_academy,
    hungarian_dance_university,
    idc_berlin,
    international_ballet_masterclasses_prague,
    intodance_athens,
    japan_ballet_association,
    japan_ballet_intensives,
    joffrey_ballet_school,
    john_cranko_school,
    k_ballet_school,
    korea_national_ballet_academy,
    la_sylphide_ballet_academy,
    les_ballets_de_pologne,
    london_childrens_ballet_summer_school,
    m_i_ballet_school,
    master_ballet_academy,
    masters_of_ballet_academy,
    mlody_balet_polski,
    mosa_ballet_school,
    munich_ballet_intensive,
    nacho_duato_academy,
    nationaltheater_mannheim,
    nba_ballet_company,
    ndt_summer_intensive,
    new_national_theatre_ballet_school,
    new_zealand_school_of_dance,
    nordsee_akademie_sommertanztage,
    northern_ballet_academy,
    norwegian_national_ballet,
    nuova_officina_della_danza,
    nuovo_balletto_classico,
    opus_ballet,
    orsolina28,
    pacific_northwest_ballet_school,
    php_ballet_intensive,
    pirueta_brno,
    pnsd_rosella_hightower,
    prague_ballet_intensive,
    prague_ballet_workshop,
    prix_de_lausanne_summer_intensive,
    professione_danza_pescara,
    progetto_danza_treviso,
    rad_japan_summer_school,
    revolve_dance_bucharest,
    rosenthal_ballett,
    royal_ballet_school,
    royal_conservatoire_the_hague,
    royal_danish_ballet_summer_school,
    royal_winnipeg_ballet_school,
    russian_masters_ballet,
    san_francisco_ballet_school,
    school_of_american_ballet,
    scuola_hamlyn,
    sommer_tanz_camp_berlin,
    staatsballett_berlin_feriencamp,
    stage_charles_jude,
    staromestske_baletne_studio,
    studio_architanz,
    summer_sensation_intensive,
    tanzquartier_koeln,
    teatro_san_carlo_scuola_ballo,
    temps_lie_ballet_workshop_japan,
    the_hammond,
    tokyo_ballet_school,
    tokyo_city_ballet,
    umbria_ballet,
    vaganova_international_program,
    verona_summer_dance_lab,
    wiener_ballettakademie,
    yagp_nervi_summer_workshop,
    yorkshire_ballet_seminars,
    young_stars_ballet,
)

Scraper = Callable[[httpx.Client], list[Offering]]

SCRAPERS: dict[str, Scraper] = {
    "abc-dance": abc_dance.scrape,
    "abt-jko-school": abt_jko_school.scrape,
    "academie-danse-biarritz": academie_danse_biarritz.scrape,
    "academie-ete-nice": academie_ete_nice.scrape,
    "academie-princesse-grace": academie_princesse_grace.scrape,
    "academie-theilaia": academie_theilaia.scrape,
    "accademia-iacopini": accademia_iacopini.scrape,
    "accademia-internazionale-coreutica": accademia_internazionale_coreutica.scrape,
    "accademia-teatro-alla-scala": accademia_teatro_alla_scala.scrape,
    "akademia-sztuki-baletowej": akademia_sztuki_baletowej.scrape,
    "alberta-ballet-school": alberta_ballet_school.scrape,
    "american-midwest-ballet": american_midwest_ballet.scrape,
    "art-ballet-gdynia": art_ballet_gdynia.scrape,
    "art-in-motion-munich": art_in_motion_munich.scrape,
    "art-of-zurich": art_of_ballet_summer_course.scrape,
    "art-studio-danza": art_studio_danza.scrape,
    "arteballetto": arteballetto.scrape,
    "associazione-europea-danza": associazione_europea_danza.scrape,
    "ateneo-della-danza": ateneo_della_danza.scrape,
    "attitude-ballet-studios": attitude_ballet_studios.scrape,
    "australian-ballet-school": australian_ballet_school.scrape,
    "baletni-akademie-pollertova": baletni_akademie_pollertova.scrape,
    "ballet-ireland": ballet_ireland.scrape,
    "ballet-ruso-barcelona": ballet_ruso_barcelona.scrape,
    "ballet-summer-course-budapest": ballet_summer_course_budapest.scrape,
    "ballet-workshops-bucharest": ballet_workshops_bucharest.scrape,
    "balletstage": balletstage.scrape,
    "ballett-dortmund": ballett_dortmund.scrape,
    "balletto-di-roma": balletto_di_roma.scrape,
    "ballettratten": ballettratten.scrape,
    "bayer-ballet-academy": bayer_ballet_academy.scrape,
    "benedict-manniegel": benedict_manniegel.scrape,
    "bobbio-summer-ballet-intensive": bobbio_summer_ballet_intensive.scrape,
    "bolshoi-summer-intensive-tokyo": bolshoi_summer_intensive_tokyo.scrape,
    "boston-ballet-school": boston_ballet_school.scrape,
    "brussels-international-ballet": brussels_international_ballet.scrape,
    "bubenicek-masterclasses": bubenicek_masterclasses.scrape,
    "canadas-national-ballet-school": canadas_national_ballet_school.scrape,
    "central-school-of-ballet": central_school_of_ballet.scrape,
    "centro-formazione-aida": centro_formazione_aida.scrape,
    "centro-formazione-danza-verona": centro_formazione_danza_verona.scrape,
    "centrum-sztuki-tanca": centrum_sztuki_tanca.scrape,
    "conservatorio-annarella": conservatorio_annarella.scrape,
    "cords-dance": cords_dance.scrape,
    "corella-dance-academy": corella_dance_academy.scrape,
    "dam-danza-torino": dam_danza_torino.scrape,
    "dance-and-fashion-cic": dance_and_fashion_cic.scrape,
    "dbft-sommerakademie": dbft_sommerakademie.scrape,
    "dd-masterclass-japan": dd_masterclass_japan.scrape,
    "dresden-summer-dance": dresden_summer_dance.scrape,
    "dutch-national-ballet-academy": dutch_national_ballet_academy.scrape,
    "ecole-danse-opera-paris": ecole_danse_opera_paris.scrape,
    "elmhurst-ballet-school": elmhurst_ballet_school.scrape,
    "english-national-ballet-school": english_national_ballet_school.scrape,
    "escola-bolshoi-brasil": escola_bolshoi_brasil.scrape,
    "europaballett-danceflash": europaballett_danceflash.scrape,
    "finland-international-summer-ballet-school": finland_international_summer_ballet_school.scrape,
    "finnish-national-ballet": finnish_national_ballet.scrape,
    "fondazione-monreart": fondazione_monreart.scrape,
    "fouette": fouette.scrape,
    "frankfurt-ballet-masterclasses": frankfurt_ballet_masterclasses.scrape,
    "goh-ballet-academy": goh_ballet_academy.scrape,
    "gradpro-summer-intensive": gradpro_summer_intensive.scrape,
    "gyori-balett-dance-intensive": gyori_balett_dance_intensive.scrape,
    "hong-kong-academy-of-ballet": hong_kong_academy_of_ballet.scrape,
    "houston-ballet-academy": houston_ballet_academy.scrape,
    "hungarian-dance-university": hungarian_dance_university.scrape,
    "idc-berlin": idc_berlin.scrape,
    "international-ballet-masterclasses-prague": international_ballet_masterclasses_prague.scrape,
    "intodance-athens": intodance_athens.scrape,
    "japan-ballet-association": japan_ballet_association.scrape,
    "japan-ballet-intensives": japan_ballet_intensives.scrape,
    "joffrey-ballet-school": joffrey_ballet_school.scrape,
    "john-cranko-schule": john_cranko_school.scrape,
    "k-ballet-school": k_ballet_school.scrape,
    "korea-national-ballet-academy": korea_national_ballet_academy.scrape,
    "la-sylphide-ballet-academy": la_sylphide_ballet_academy.scrape,
    "les-ballets-de-pologne": les_ballets_de_pologne.scrape,
    "london-childrens-ballet-summer-school": london_childrens_ballet_summer_school.scrape,
    "m-i-ballet-school": m_i_ballet_school.scrape,
    "master-ballet-academy": master_ballet_academy.scrape,
    "masters-of-ballet-academy": masters_of_ballet_academy.scrape,
    "mlody-balet-polski": mlody_balet_polski.scrape,
    "mosa-ballet-school": mosa_ballet_school.scrape,
    "munich-ballet-intensive": munich_ballet_intensive.scrape,
    "nacho-duato-academy": nacho_duato_academy.scrape,
    "nationaltheater-mannheim": nationaltheater_mannheim.scrape,
    "nba-ballet-company": nba_ballet_company.scrape,
    "ndt-summer-intensive": ndt_summer_intensive.scrape,
    "new-national-theatre-ballet-school": new_national_theatre_ballet_school.scrape,
    "new-zealand-school-of-dance": new_zealand_school_of_dance.scrape,
    "nordsee-akademie-sommertanztage": nordsee_akademie_sommertanztage.scrape,
    "northern-ballet-academy": northern_ballet_academy.scrape,
    "norwegian-national-ballet": norwegian_national_ballet.scrape,
    "nuova-officina-della-danza": nuova_officina_della_danza.scrape,
    "nuovo-balletto-classico": nuovo_balletto_classico.scrape,
    "opus-ballet": opus_ballet.scrape,
    "orsolina28": orsolina28.scrape,
    "pacific-northwest-ballet-school": pacific_northwest_ballet_school.scrape,
    "php-ballet-intensive": php_ballet_intensive.scrape,
    "pirueta-brno": pirueta_brno.scrape,
    "pnsd-rosella-hightower": pnsd_rosella_hightower.scrape,
    "prague-ballet-intensive": prague_ballet_intensive.scrape,
    "prague-ballet-workshop": prague_ballet_workshop.scrape,
    "prix-de-lausanne-summer-intensive": prix_de_lausanne_summer_intensive.scrape,
    "professione-danza-pescara": professione_danza_pescara.scrape,
    "progetto-danza-treviso": progetto_danza_treviso.scrape,
    "rad-japan-summer-school": rad_japan_summer_school.scrape,
    "revolve-dance-bucharest": revolve_dance_bucharest.scrape,
    "rosenthal-ballett": rosenthal_ballett.scrape,
    "royal-ballet-school": royal_ballet_school.scrape,
    "royal-conservatoire-the-hague": royal_conservatoire_the_hague.scrape,
    "royal-danish-ballet-summer-school": royal_danish_ballet_summer_school.scrape,
    "royal-winnipeg-ballet-school": royal_winnipeg_ballet_school.scrape,
    "russian-masters-ballet": russian_masters_ballet.scrape,
    "san-francisco-ballet-school": san_francisco_ballet_school.scrape,
    "school-of-american-ballet": school_of_american_ballet.scrape,
    "scuola-hamlyn": scuola_hamlyn.scrape,
    "sommer-tanz-camp-berlin": sommer_tanz_camp_berlin.scrape,
    "staatsballett-berlin-feriencamp": staatsballett_berlin_feriencamp.scrape,
    "stage-charles-jude": stage_charles_jude.scrape,
    "staromestske-baletne-studio": staromestske_baletne_studio.scrape,
    "studio-architanz": studio_architanz.scrape,
    "summer-sensation-intensive": summer_sensation_intensive.scrape,
    "tanzquartier-koeln": tanzquartier_koeln.scrape,
    "teatro-san-carlo-scuola-ballo": teatro_san_carlo_scuola_ballo.scrape,
    "temps-lie-ballet-workshop-japan": temps_lie_ballet_workshop_japan.scrape,
    "the-hammond": the_hammond.scrape,
    "tokyo-ballet-school": tokyo_ballet_school.scrape,
    "tokyo-city-ballet": tokyo_city_ballet.scrape,
    "umbria-ballet": umbria_ballet.scrape,
    "vaganova-international-program": vaganova_international_program.scrape,
    "verona-summer-dance-lab": verona_summer_dance_lab.scrape,
    "wiener-ballettakademie": wiener_ballettakademie.scrape,
    "yagp-nervi-summer-workshop": yagp_nervi_summer_workshop.scrape,
    "yorkshire-ballet-seminars": yorkshire_ballet_seminars.scrape,
    "young-stars-ballet": young_stars_ballet.scrape,
}
